name: Generar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Instalar dependencias
        run: npm install

      - name: Crear proyecto Android
        run: npx cap add android

      - name: Sincronizar aplicación
        run: npx cap sync android

      - name: Compilar APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: mi-leon-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
